"""empty message

Revision ID: 7b7f97aa8fc5
Revises: 
Create Date: 2025-02-14 19:44:54.955289

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b7f97aa8fc5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False),
    sa.Column('referrer_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('user_email_hash_index', 'user', ['email'], unique=False, postgresql_using='hash')
    op.create_index('user_id_hash_index', 'user', ['id'], unique=False, postgresql_using='hash')
    op.create_table('referralcode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('code_expiration', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referralcode')
    op.drop_index('user_id_hash_index', table_name='user', postgresql_using='hash')
    op.drop_index('user_email_hash_index', table_name='user', postgresql_using='hash')
    op.drop_table('user')
    # ### end Alembic commands ###
